version: '3.8'
services:
  postgres-img-uploader:
    container_name: postgres-img-uploader
    image: postgres
    environment:
      POSTGRES_USER: dbwarehouse
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: img-uploader
      PGDATA: /data/postgres
    volumes:
      - postgres-img-uploader:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres-img-uploader: