server:
  port: 8080
spring:
  application:
    name: amazon-image-uploader
  servlet:
    multipart:
      max-file-size: 50MB
  datasource:
    password: 123456
    url: jdbc:postgresql://localhost:5432/warehouse
    username: dbwarehouse
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true